### PR TITLE
Updates for 2022-2.2 envs

### PR DESCRIPTION
**Pull request by AbbyGi**
TODOs:
- [x] pin the latest version of `scipy`
- [x] add `prefect`
- [x] add `bluesky-queueserver-api`

### CODE REVIEW

**Comment by mrakitin** [comment]
The problem with scipy>=1.8 is that it does not exist for Python 3.7:
```bash
$ conda search 'scipy=1.8=py37*[channel=conda-forge, subdir=linux-64]'
Loading channels: done
No match found for: conda-forge/linux-64::scipy==1.8[build=py37*]. Search: conda-forge/linux-64::*scipy*==1.8[build=py37*]

PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge/linux-64::scipy==1.8[build=py37*]

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


$ conda search 'scipy=1.8=py38*[channel=conda-forge, subdir=linux-64]'
Loading channels: done
# Name                       Version           Build  Channel
scipy                          1.8.0  py38h56a6a73_0  conda-forge
scipy                          1.8.0  py38h56a6a73_1  conda-forge
```

We can try switching from Python 3.7 -> 3.8 for now, as `diffpy` is supported on that version of Python.

**Comment by mrakitin** [comment]
Downloaded the py38 test env from https://github.com/nsls2-conda-envs/nsls2-collection-tiled/actions/runs/2190779095 and installed `diffpy` locally. It imports successfully, so we can switch to py38 as a minimum Python version.

**Comment by mrakitin** [comment]
@gwbischof, I think it's ready to go. I added `bluesky-queueserver-api` from PyPI for Python 3.9 for now as it had some conflicts if installed from conda-forge.

**Review by gwbischof — APPROVED** [review]

**Comment by mrakitin** [comment]
Published on Zenodo: https://zenodo.org/record/6499325.

**Pull request merged**
