### PR TITLE
2024-2.0 tiled envs

### PR DESCRIPTION
**Pull request by mrakitin**
New `databroker`/`tiled` + `pipx` dependencies.
Most likely won't update the non-`tiled` envs this time.

```diff
❯ diff envs/env-py310.yml envs/env-py311.yml
1c1
< name: 2024-2.0-py310-tiled
---
> name: 2024-2.0-py311-tiled
10c10
<   - python >=3.10,<3.11
---
>   - python >=3.11,<3.12
```

## TODOs:
- [x] `event-model` v1.20.0 on PyPI.
- [x] `suitecase-mongo` v0.6.0
- [x] `tiled` v0.1.0a117.

### CODE REVIEW

**Review by danielballan — APPROVED** [review]

**Comment by mrakitin** [comment]
https://github.com/nsls2-conda-envs/nsls2-collection-tiled/pull/32 is supposed to solve the building issues.

**Review by danielballan — APPROVED** [review]

**Comment by mrakitin** [comment]
I'll merge it once the CI passes for the latest commit.

**Comment by mrakitin** [comment]
After a successful run last Sunday, next Monday the builds started failing. Still trying to fix the issue...

**Comment by mrakitin** [comment]
Trying to reproduce locally with:
```
act -W .github/workflows/package.yml -j generate_conda_packd_envs --matrix python-version:3.10
```

**Pull request merged**
