### PR TITLE
2023-1.0 envs

### PR DESCRIPTION
**Pull request by mrakitin**
Consistent changes with https://github.com/nsls2-conda-envs/nsls2-collection/pull/13.

Diffs:
```diff
$ diff configs/config-py39.yml configs/config-py310.yml
2,3c2,3
< env_name: "2023-1.0-py39-tiled"
< conda_env_file: "env-py39.yml"
---
> env_name: "2023-1.0-py310-tiled"
> conda_env_file: "env-py310.yml"
5c5
< python_version: "3.9"
---
> python_version: "3.10"
```

```diff
$ diff envs/env-py39.yml envs/env-py310.yml
1c1
< name: 2023-1.0-py39-tiled
---
> name: 2023-1.0-py310-tiled
10c10
<   - python >=3.9,<3.10
---
>   - python >=3.10,<3.11
```

```diff
$ diff nsls2-collection/envs/env-py39.yml nsls2-collection-tiled/envs/env-py39.yml
1c1
< name: 2023-1.0-py39
---
> name: 2023-1.0-py39-tiled
29,30c29
<   - databroker >=1.2.5,<2.0.0a
<   - databroker-pack
---
>   - databroker >=2.0.0b13=*_0
51d49
<   - intake <=0.6.4
127a126
>   - tiled >=0.1.0a80
```

```diff
$ diff nsls2-collection/envs/env-py310.yml nsls2-collection-tiled/envs/env-py310.yml
1c1
< name: 2023-1.0-py310
---
> name: 2023-1.0-py310-tiled
29,30c29
<   - databroker >=1.2.5,<2.0.0a
<   - databroker-pack
---
>   - databroker >=2.0.0b13=*_0
51d49
<   - intake <=0.6.4
127a126
>   - tiled >=0.1.0a80
```

### CODE REVIEW

**Comment by mrakitin** [comment]
@jklynch, @tacaswell, could you please review?

**Comment by mrakitin** [comment]
Ready for review again! I sync'd the changes with the `nsls2-collection` PR.

**Review by tacaswell — APPROVED** [review]

**Comment by maffettone** [comment]
Duplicate of this: https://github.com/nsls2-conda-envs/nsls2-collection/pull/13#issuecomment-1361446122

Very pleased, one thing worth double checking.

**Comment by mrakitin** [comment]
Thanks for the reviews!

**Comment by mrakitin** [comment]
Deposited to https://zenodo.org/record/7470912 via https://github.com/nsls2-conda-envs/playground/actions/runs/3753798831/jobs/6377399827.

**Pull request merged**
